app: souravtest
service: chatapi
frameworkVersion: "2"

provider:
  name: aws
  stage: dev
  region: ap-south-1
  profile: personal

plugins:
  - serverless-plugin-typescript

functions:
  # Create a Lambda function that responds to messages for the predefined routes
  websocket:
    handler: src/websocket/routes.handler
    events:
      - websocket:
          # Handles new connection requests
          route: $connect

      - websocket:
          # Route messages here if '$request.body.action' is 'routeA'.
          # You can adjust which property to use for routing by adjusting
          # 'websocketsApiRouteSelectionExpression'.
          route: heartbeat

      - websocket:
          route: notify

      - websocket:
          # Handles all unrouted messages
          route: $default

      - websocket:
          # Handles disconnect messages
          route: $disconnect

resources: # CloudFormation template syntax from here on.
  Resources:
    connectedClientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: connectedClientsTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: emailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: "ALL"
        BillingMode: PAY_PER_REQUEST
